# Generated by Django 5.0 on 2024-10-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='port',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
