# Generated by Django 4.2 on 2024-08-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
