# Generated by Django 4.2 on 2024-08-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
