# Generated by Django 4.2 on 2024-08-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_food_cityfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restoraunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ресторан')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Блюдо')),
                ('restoraunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restoraunt', verbose_name='Заведение')),
            ],
        ),
    ]
