# Generated by Django 4.2 on 2024-08-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_restoraunt_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoraunt',
            name='slug',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
