# Generated by Django 4.2 on 2024-08-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_restoraunt_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.URLField(max_length=1000, null=True, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='restoraunt',
            name='owner',
            field=models.TextField(max_length=7000, null=True),
        ),
        migrations.AddField(
            model_name='restoraunt',
            name='schedule',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='RestorauntDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.dish')),
                ('restoraunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restoraunt')),
            ],
        ),
    ]
