# Generated by Django 4.2 on 2024-09-03 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoraunt',
            name='image',
            field=models.CharField(max_length=2000, null=True, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='cityfood',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='food.city', verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='restoraunt',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restoraunts', to='food.city', verbose_name='Город'),
        ),
    ]
