# Generated by Django 4.2 on 2024-09-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_restoraunt_image_alter_cityfood_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='genitive_case',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
