# Generated by Django 4.2 on 2024-09-04 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_city_genitive_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestorauntFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('restoraunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restoraunt')),
            ],
        ),
    ]
