# Generated by Django 5.0 on 2024-10-06 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_restorauntfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='food.dishcategory', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='restoraunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='food.restoraunt', verbose_name='Заведение'),
        ),
        migrations.AlterField(
            model_name='restorauntdish',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_restoraunts', to='food.dish'),
        ),
        migrations.AlterField(
            model_name='restorauntfood',
            name='restoraunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='food.restoraunt'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['id'], name='food_dish_id_907f30_idx'),
        ),
    ]
