# Generated by Django 5.0 on 2024-10-07 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_alter_dish_category_alter_dish_restoraunt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(max_length=100, verbose_name='страница')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=3000)),
            ],
        ),
        migrations.AlterField(
            model_name='cityfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_foods', to='food.food', verbose_name='кухня'),
        ),
        migrations.AlterField(
            model_name='restorauntfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoraunt_foods', to='food.food'),
        ),
    ]
