# Generated by Django 5.0 on 2024-10-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_seo_alter_cityfood_food_alter_restorauntfood_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'Seo', 'verbose_name_plural': 'Seo'},
        ),
        migrations.RemoveIndex(
            model_name='dish',
            name='food_dish_id_907f30_idx',
        ),
        migrations.AlterField(
            model_name='seo',
            name='page_type',
            field=models.CharField(choices=[('Главная', 'Главная'), ('Город', 'Город')], max_length=100, verbose_name='страница'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['id', 'restoraunt_id', 'category_id'], name='food_dish_id_dfb13f_idx'),
        ),
    ]
