# Generated by Django 5.0 on 2024-10-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_alter_seo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoraunt',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='seo',
            name='page_type',
            field=models.CharField(choices=[('Главная', 'Главная'), ('Город', 'Город'), ('Ресторан', 'Ресторан')], max_length=100, verbose_name='страница'),
        ),
    ]
