# Generated by Django 5.0 on 2024-10-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_restoraunt_address_alter_seo_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='genitive_case',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
