# Generated by Django 5.0 on 2024-10-31 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0021_restorauntref_alter_city_options_alter_dish_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestorauntRef",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ref", models.URLField(verbose_name="ссылка")),
                ("text", models.CharField(default="Заказать", max_length=50)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="dish",
            name="food_dish_id_dfb13f_idx",
        ),
        migrations.AddField(
            model_name="dish",
            name="price",
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="Цена"),
        ),
        migrations.AddField(
            model_name="dish",
            name="weight",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Вес"),
        ),
        migrations.AddField(
            model_name="restoraunt",
            name="min_order",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="restoraunt",
            name="price_category",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="dish",
            name="slug",
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name="restorauntref",
            name="restoraunt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="refs", to="food.restoraunt"
            ),
        ),
    ]
