# Generated by Django 5.0 on 2024-10-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0022_restorauntref_remove_dish_food_dish_id_dfb13f_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.CharField(max_length=10, null=True, verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="dish",
            name="slug",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="dish",
            name="unique_key",
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
