# Generated by Django 5.0 on 2024-11-02 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0023_alter_dish_price_alter_dish_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restorauntref",
            options={"verbose_name": "ссылка для ресторана", "verbose_name_plural": "ссылки для ресторана"},
        ),
        migrations.AlterField(
            model_name="restoraunt",
            name="address",
            field=models.CharField(max_length=500, null=True, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="restoraunt",
            name="min_order",
            field=models.CharField(max_length=20, null=True, verbose_name="Минимальный заказ"),
        ),
        migrations.AlterField(
            model_name="restoraunt",
            name="owner",
            field=models.TextField(max_length=7000, null=True, verbose_name="Владелец"),
        ),
        migrations.AlterField(
            model_name="restoraunt",
            name="price_category",
            field=models.CharField(max_length=20, null=True, verbose_name="Ценовая категория"),
        ),
        migrations.AlterField(
            model_name="restoraunt",
            name="schedule",
            field=models.CharField(max_length=300, null=True, verbose_name="Расписание"),
        ),
        migrations.CreateModel(
            name="DishRef",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ref", models.URLField(verbose_name="ссылка")),
                ("text", models.CharField(default="Заказать", max_length=50)),
                ("dish", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="food.dish")),
            ],
            options={
                "verbose_name": "ссылка для блюда",
                "verbose_name_plural": "ссылки для блюда",
            },
        ),
    ]
