# Generated by Django 5.0 on 2024-11-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0024_alter_restorauntref_options_alter_restoraunt_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restoraunt",
            name="unique_key",
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
