# Generated by Django 5.0 on 2024-11-08 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0025_restoraunt_unique_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, verbose_name="Магазин")),
                ("image", models.URLField(max_length=100, verbose_name="Изображение")),
                ("address", models.CharField(max_length=50, verbose_name="Адрес")),
                ("min_order", models.CharField(max_length=10, verbose_name="Минимальный заказ")),
                ("price_category", models.CharField(max_length=10, verbose_name="Ценовая категория")),
            ],
            options={
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
            },
        ),
        migrations.AlterField(
            model_name="dish",
            name="slug",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="restoraunt",
            name="unique_key",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="CityShop",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(max_length=100)),
                ("unique_key", models.CharField(max_length=30, unique=True)),
                ("city", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="food.city")),
                ("shop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="food.shop")),
            ],
            options={
                "verbose_name": "Магазин в городе",
                "verbose_name_plural": "Магазины в городах",
            },
        ),
    ]
