# Generated by Django 5.0 on 2024-11-09 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0028_cityshop_unique_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Категория товаров")),
            ],
            options={
                "verbose_name": "Категория товаров",
                "verbose_name_plural": "Категории товаров",
            },
        ),
        migrations.AlterField(
            model_name="cityshop",
            name="city",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shops", to="food.city"),
        ),
        migrations.AlterField(
            model_name="cityshop",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="city_shops", to="food.shop"
            ),
        ),
        migrations.CreateModel(
            name="ShopProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Товар")),
                ("image", models.URLField(max_length=1000, null=True, verbose_name="Изображение")),
                ("slug", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=10, null=True, verbose_name="Цена")),
                ("weight", models.CharField(blank=True, max_length=15, null=True, verbose_name="Вес")),
                ("unique_key", models.CharField(max_length=40, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="food.shopcategory",
                        verbose_name="категория",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="food.cityshop", verbose_name="магазин"
                    ),
                ),
            ],
        ),
    ]
