# Generated by Django 5.0 on 2025-11-21 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0030_alter_shopproduct_options_dishref_unique_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishref",
            name="dish",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="refs", to="food.dish"),
        ),
        migrations.AlterField(
            model_name="restoraunt",
            name="unique_key",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
