# Generated by Django 5.0 on 2024-11-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0032_alter_dish_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="unique_key",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
