# Generated by Django 5.0 on 2024-11-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0033_alter_dish_unique_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="slug",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="dish",
            name="unique_key",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
