# Generated by Django 5.0 on 2024-12-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0036_alter_dish_unique_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="unique_key",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
