# Generated by Django 5.0 on 2024-12-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0038_alter_dish_unique_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="unique_key",
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
