# Generated by Django 5.0 on 2024-12-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0040_alter_shop_address_alter_shop_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Магазин"),
        ),
    ]
