# Generated by Django 5.0 on 2024-12-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0041_alter_shop_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopproduct",
            name="unique_key",
            field=models.CharField(max_length=40),
        ),
    ]
