# Generated by Django 5.0 on 2024-12-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0042_alter_shopproduct_unique_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopproduct",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Товар"),
        ),
    ]
