# Generated by Django 5.0 on 2024-12-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0043_alter_shopproduct_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishref",
            name="unique_key",
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="restorauntref",
            name="unique_key",
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
