# Generated by Django 5.0 on 2024-12-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0044_alter_dishref_unique_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dishref",
            name="ref",
            field=models.URLField(max_length=350, verbose_name="ссылка"),
        ),
        migrations.AlterField(
            model_name="restorauntref",
            name="ref",
            field=models.URLField(max_length=350, verbose_name="ссылка"),
        ),
    ]
