# Generated by Django 5.0 on 2024-12-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0045_alter_dishref_ref_alter_restorauntref_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="seo",
            name="text",
            field=models.TextField(blank=True, max_length=7000, null=True),
        ),
        migrations.AlterField(
            model_name="seo",
            name="page_type",
            field=models.CharField(
                choices=[("Главная", "Главная"), ("Город", "Город"), ("Ресторан", "Ресторан"), ("Кухня", "Кухня")],
                max_length=100,
                verbose_name="страница",
            ),
        ),
    ]
