# Generated by Django 5.0 on 2024-12-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0047_alter_seo_text"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dish",
            index=models.Index(fields=["restoraunt_id"], name="food_dish_restora_518a65_idx"),
        ),
    ]
