# Generated by Django 5.0 on 2024-12-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0048_dish_food_dish_restora_518a65_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexPageButton",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ref", models.CharField(max_length=400, verbose_name="ссылка")),
                ("text", models.CharField(default="Заказать", max_length=50, verbose_name="текст")),
            ],
            options={
                "verbose_name": "Кнопка на главной",
                "verbose_name_plural": "Кнопки на главной",
            },
        ),
    ]
