# Generated by Django 5.0 on 2025-01-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0049_indexpagebutton"),
    ]

    operations = [
        # migrations.RemoveField(
        #    model_name='cityfood',
        #    name='city',
        # ),
        # migrations.RemoveField(
        #    model_name='cityfood',
        #    name='food',
        # ),
        # migrations.AlterField(
        #    model_name='dish',
        #    name='unique_key',
        #    field=models.CharField(max_length=300, null=True),
        # ),
        migrations.AddIndex(
            model_name="dish",
            index=models.Index(fields=["restoraunt_id"], name="food_dish_restoraunt_518a65_idx"),
        ),
        # migrations.DeleteModel(
        #    name='CityFood',
        # ),
    ]
