# Generated by Django 5.0 on 2025-03-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0050_remove_cityfood_city_remove_cityfood_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='h1',
            field=models.CharField(blank=True, max_length=300, null=True),
        )
    ]
