# Generated by Django 5.0 on 2025-03-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0051_remove_cityfood_city_remove_cityfood_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityfood',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cityfood',
            name='food',
        ),
        migrations.RemoveIndex(
            model_name='dish',
            name='food_dish_restoraunt_518a65_idx',
        ),
        migrations.AddField(
            model_name='restoraunt',
            name='rating',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='unique_key',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='seo',
            name='page_type',
            field=models.CharField(choices=[('Главная', 'Главная'), ('Город', 'Город'), ('Ресторан', 'Ресторан'), ('Магазин', 'Магазин'), ('Кухня', 'Кухня')], max_length=100, verbose_name='страница'),
        ),
        migrations.DeleteModel(
            name='CityFood',
        ),
    ]
