# Generated by Django 5.0 on 2025-03-08 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0052_remove_cityfood_city_remove_cityfood_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restoraunt',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restoraunts', to='food.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='restoraunt',
            name='rating',
            field=models.CharField(max_length=3, null=True, verbose_name='Рейтинг'),
        ),
    ]
