# Generated by Django 5.0 on 2025-03-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0053_alter_restoraunt_city_alter_restoraunt_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restoraunt',
            name='rating',
        ),
    ]
