# Generated by Django 5.0 on 2025-03-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0054_remove_restoraunt_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restoraunt',
            name='rating',
            field=models.CharField(max_length=3, null=True, verbose_name='Рейтинг'),
        ),
    ]
