# Generated by Django 5.0 on 2025-03-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0055_restoraunt_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestorauntPageButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=400, verbose_name='ссылка')),
                ('text', models.CharField(default='Заказать', max_length=50, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'Кнопка на странице ресторанов',
                'verbose_name_plural': 'Кнопки на странице ресторанов',
            },
        ),
        migrations.CreateModel(
            name='ShopPageButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=400, verbose_name='ссылка')),
                ('text', models.CharField(default='Заказать', max_length=50, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'Кнопка на странице магазинов',
                'verbose_name_plural': 'Кнопки на странице магазинов',
            },
        ),
    ]
