# Generated by Django 5.0 on 2025-03-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0056_restorauntpagebutton_shoppagebutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpagebutton',
            name='type',
            field=models.CharField(choices=[('Яндекс', 'Яндекс'), ('Деливери', 'Деливери')], default='Яндекс', max_length=10, verbose_name='сервис'),
        ),
        migrations.AddField(
            model_name='restorauntpagebutton',
            name='type',
            field=models.CharField(choices=[('Яндекс', 'Яндекс'), ('Деливери', 'Деливери')], default='Яндекс', max_length=10, verbose_name='сервис'),
        ),
        migrations.AddField(
            model_name='shoppagebutton',
            name='type',
            field=models.CharField(choices=[('Яндекс', 'Яндекс'), ('Деливери', 'Деливери')], default='Яндекс', max_length=10, verbose_name='сервис'),
        ),
    ]
