# Generated by Django 5.0 on 2025-03-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0057_indexpagebutton_type_restorauntpagebutton_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishref',
            name='unique_key',
        ),
        migrations.RemoveField(
            model_name='restorauntref',
            name='unique_key',
        ),
        migrations.AddField(
            model_name='cityshop',
            name='rating',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
