# Generated by Django 5.0 on 2025-04-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0058_remove_dishref_unique_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='h2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
